name: skeleton_kosmos
description: A new Flutter package project.
version: 3.2.0
publish_to: none
homepage: none
environment:
  sdk: '>=2.16.2 <3.0.0'
  flutter: '>=1.17.0'
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.19.2
  firebase_auth: ^3.4.2
  cloud_firestore: ^3.3.0
  cloud_functions: ^3.3.2
  firebase_storage: ^10.3.2
  firebase_messaging: ^12.0.0
  country_picker: ^2.0.16
  google_maps_flutter: ^2.1.9
  geolocator: ^9.0.1
  geoflutterfire: ^3.0.3
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  auto_route: ^4.2.1
  url_strategy: ^0.2.0
  hooks_riverpod: ^1.0.3
  get_it: ^7.2.0
  get: ^4.6.5
  dartz: ^0.10.1
  responsive_framework: ^0.2.0
  flutter_screenutil: ^5.5.3+2
  easy_localization: 3.0.1
  universal_io: ^2.0.4
  fluttertoast: ^8.0.9
  path: ^1.8.1
  cached_network_image: ^3.2.1
  image_picker: ^0.8.5+3
  mime_type: ^1.0.0
  expandable_page_view: ^1.0.17
  url_launcher: ^6.1.5
  pin_code_fields: ^7.4.0
  sliding_up_panel: ^2.0.0+1
  localstorage: ^4.0.0+1
  shared_preferences: ^2.0.15
  flutter_native_splash: ^2.2.14
  dartdoc: ^6.0.0
  core_kosmos:
    git:
      publish_to: none
      url: YOUR_URL
      ref: main
  ui_kosmos_v4:
    git:
      publish_to: none
      url: YOUR_URL
      ref: main
  form_generator_kosmos:
    git:
      publish_to: none
      url: YOUR_URL
      ref: main
  settings_kosmos:
    git:
      publish_to: none
      url: YOUR_URL
      ref: main
  auth_helper:
    git:
      publish_to: none
      url: YOUR_URL
      ref: main
  permissionrequest:
    git:
      publish_to: none
      url: YOUR_URL
      ref: main
  onboarding_kosmos:
    git:
      publish_to: none
      url: YOUR_URL
      ref: main
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.2.0
flutter:
  uses-material-design: true
  fonts:
  - family: Poppins
    fonts:
    - asset: assets/fonts/Poppins-Light.ttf
      weight: 300
    - asset: assets/fonts/Poppins-Regular.ttf
      weight: 400
    - asset: assets/fonts/Poppins-Medium.ttf
      weight: 500
    - asset: assets/fonts/Poppins-SemiBold.ttf
      weight: 600
    - asset: assets/fonts/Poppins-Bold.ttf
      weight: 700
  assets:
  - assets/fonts/
  - assets/images/
